version: '3'
services:
  ui:
    image: node:18.9.0-alpine3.15
    command: ash -c "npm install && npm run dev"
    volumes:
        - ./ui:/home/node
    working_dir: /home/node
    ports:
        - "5000:5000"
        - "35730:35730"
    environment:
      - API_ADDRESS
      - MEDIA_ADDRESS


