version: '3'
services:
  server:
    build: ./server
    volumes:
      - ./ui/build:/var/www/html
      - ${HOST_MEDIA_PATH}:/${MEDIA_PATH}
    ports:
      - "8000:80"

  ui:
    image: node:18.9.0-alpine3.15
    command: ash -c "npm install && npm start"
    volumes:
        - ./ui:/home/node
    working_dir: /home/node
    ports:
        - "5000:5000"
        - "35730:35730"
    environment:
      - REACT_APP_API_ADDRESS=$API_ADDRESS
      - REACT_APP_MEDIA_ADDRESS=$MEDIA_ADDRESS

  api:
    build: ./api
    working_dir: /home/api
    command: ash -c "echo -n $$MEDIA_PATH > service/media_url.txt &&
                     echo -n $$DB_ADDRESS > service/db_address.txt &&
                     air -c ./air.toml"
    volumes:
      - ./api:/home/api
      - ${HOST_MEDIA_PATH}:/${MEDIA_PATH}
    ports:
      - "3000:3000"
    environment:
      - DB_ADDRESS
      - MEDIA_PATH

  db:
    image: redis:7.0.5-alpine
